## Numpy

In [25]:
import numpy as np

In [26]:
my_list=list(range(0,9))


arr=np.array(my_list)

In [27]:
type(arr)

numpy.ndarray

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
arr.shape #One dimensional Array

(9,)

In [30]:
arr.reshape(3,3) #converting into 2 dimensional array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
my_list=list(range(0,9))
my_list1=list(range(1,10))
my_list2=list(range(2,11))

arr2=np.array([my_list,my_list1,my_list2])

In [32]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [33]:
arr2.shape #output: (no_of_rows, no_of_columns)

(3, 9)

In [34]:
arr2.reshape(9,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Indexing

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
arr[3]

3

In [37]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [38]:
arr2[1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr2[1][1]

2

In [40]:
arr2[1,1]

2

In [41]:
arr2[1:,:2]

array([[1, 2],
       [2, 3]])

In [42]:
arr2[:,3:]

array([[ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### Copy Function and broadcasting

In [51]:
arr[3:]=100 

In [52]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [55]:
arr1=arr

In [56]:
arr1[3:]=500
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]


The parent numpy array `arr` will also have its values changed as numpy array are 
reference type. In reference type both of the array will share same memory address.
In order to preent this we have **copy()** function.

In [58]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [59]:
arr1=arr.copy()

In [60]:
arr1[3:]=100
print(arr1)
print(arr)

[  0   1   2 100 100 100 100 100 100 100]
[  0   1   2 500 500 500 500 500 500 500]


Now we can see that only `arr1` values are changed

In [46]:
arr=np.arange(0,10) #arange([start,] stop[, step,], dtype=None, *, like=None)
#Return evenly spaced values within a given interval.

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.linspace(0,10,50) #Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Some conditions very useful in Exploratory Data Analysis

In [61]:
val=2

arr[arr>val]

array([500, 500, 500, 500, 500, 500, 500])

In [63]:
arr1*arr

array([    0,     1,     4, 50000, 50000, 50000, 50000, 50000, 50000,
       50000])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [66]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [74]:
# Random Distribution

np.random.rand(3,3)

array([[0.4530228 , 0.75555912, 0.52845645],
       [0.64569099, 0.44675889, 0.48096018],
       [0.0741171 , 0.65647461, 0.89243456]])

In [72]:
arr_ex=np.random.randn(4,4) #standar normal distribution

In [73]:
arr_ex

array([[-0.14288556, -0.33561004,  2.07631577,  0.10931494],
       [-1.40345556,  0.67794707,  1.78725382,  0.05217095],
       [-0.98335299,  0.01113286,  2.04079718,  0.71902663],
       [-0.30945544,  0.78608417,  0.48182049, -0.045511  ]])

In [75]:
np.random.randint(0,100,8).reshape(4,2)

array([[ 2, 85],
       [16, 61],
       [38, 21],
       [39, 92]])

In [77]:
np.random.random_sample(5)

array([0.37447635, 0.40688097, 0.74514054, 0.96061221, 0.25011537])