In [1]:
import numpy as np
print(np.__version__)

1.26.2


## __Create A numpy array filled with 10 zeros__

In [2]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## __Create a numpy arrays with values ranging from 10to49__

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## __Create a numpy matrix of 2*2 filled with ones__

In [8]:
np.array([1]*4).reshape(2,2)

array([[1, 1],
       [1, 1]])

In [11]:
np.ones([2,2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

## __Create a numpy matrix of 3*2 float ones__

In [17]:
a=np.ones([3,2], dtype=float)

In [18]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### __Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.__

In [23]:
X=np.arange(4, dtype=np.int8).reshape(2,2)

In [24]:
np.ones_like(X)

array([[1, 1],
       [1, 1]], dtype=int8)

### __Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.__

In [27]:
X=np.arange(100, dtype=np.int8).reshape(4,5,5)

In [28]:
np.zeros_like(X)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

## __Create a numpy matrix of 4*4 integers, filled with fives.__

In [29]:
np.ones([4,4], dtype=np.int8)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

### __Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.__

In [31]:
X=np.arange(49).reshape(7,7)

In [33]:
np.ones_like(X)*7

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

## __Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.__

In [3]:
np.identity(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## __Create a numpy array, filled with 3 random integer values between 1 and 10.__

In [7]:
np.random.randint(10, size=3)

array([6, 0, 9])

## __Create a 3\*3\*3 numpy matrix, filled with random float values.__

In [12]:
np.random.uniform(100, size=(3,3,3))

array([[[ 1.27268444, 45.78763072, 32.66249179],
        [36.71050311, 99.23552686, 43.50163591],
        [17.71520473, 50.70653551, 23.9883311 ]],

       [[92.5279462 , 92.9028968 , 27.25282   ],
        [33.70196089, 83.0423185 , 28.92920066],
        [62.62330478, 95.32499268,  1.7620164 ]],

       [[75.50897631, 89.98545862, 55.83724059],
        [20.8562553 ,  7.84070088, 80.10688766],
        [94.25725201, 21.26032832, 88.90919774]]])

In [10]:
np.random.randn(3,3,3)

array([[[-2.59448609,  2.1661206 ,  2.24996551],
        [-2.04895487,  0.24543163,  1.22984333],
        [ 0.41352028, -0.45584616,  0.58392554]],

       [[ 1.11689008, -1.52484373,  1.23405454],
        [ 0.67999612,  1.10891143,  1.06079394],
        [ 0.70366801,  0.9896751 , -0.23295808]],

       [[ 0.04397099, -0.26360133, -0.58902829],
        [ 1.53294586, -0.0890642 , -1.4562339 ],
        [-0.98721936, -0.38513704, -0.67670173]]])

## __Given the X python list convert it to an Y numpy array__

In [19]:
X=[1,2,3,4]

In [24]:
print(X, type(X))

[1, 2, 3, 4] <class 'list'>


In [22]:
Y=np.array(X)

In [25]:
print(Y, type(Y))

[1 2 3 4] <class 'numpy.ndarray'>


## __Given the X numpy array, make a copy and store it on Y.__

In [28]:
x=np.array([5,5,5])

In [29]:
y=np.copy(x)

In [30]:
y

array([5, 5, 5])

## __Create a numpy array with numbers from 1 to 10__

In [5]:
x=np.arange(1,11)

In [6]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## __Create a numpy array with numbers from 1 to 10__

In [7]:
X=np.arange(1,11,2)

In [8]:
X

array([1, 3, 5, 7, 9])

## __Create a numpy array with numbers from 1 to 10, in descending order.__

In [13]:
X=np.arange(1,11)[::-1]

In [14]:
X

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## __Create a 3*3 numpy matrix, filled with values ranging from 0 to 8__

In [15]:
X=np.arange(0,9).reshape(3,3)

In [17]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## __Create a 3*3 numpy matrix, filled with values ranging from 0 to 8__

In [18]:
Z=np.zeros((10,10))

In [24]:
print(Z.size*Z.itemsize) # size gives no. of element and itemsize gives memory usage of a single element

800


### __Array Indexation__

## __Create a 3*3 numpy matrix print the 1st element__

In [25]:
X=np.arange(0,9).reshape(3,3)

In [27]:
X[0][0]

0

## __Given the X numpy array, show it's last element__

In [28]:
X=np.array([1,2,3,4])

In [30]:
X[-1]

4

## __Given the X numpy array, show it's first three elements__

In [39]:
X=np.arange(1,5)

In [40]:
X

array([1, 2, 3, 4])

In [42]:
X[0:3]

array([1, 2, 3])

## __Given the X numpy array, show all middle elements__

In [43]:
X=np.arange(1,10)

In [44]:
X[1:-1]

array([2, 3, 4, 5, 6, 7, 8])

## __Given the X numpy array, show the elements in reverse position__

In [45]:
X=np.arange(10)

In [47]:
X[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## __Given the X numpy array, show the elements in an odd position__

In [48]:
X=np.arange(10)

In [52]:
X[::2]

array([0, 2, 4, 6, 8])

## __Given the X numpy matrix, show the first row elements__

In [54]:
X=np.arange(15).reshape(5,3)

In [55]:
X[0]

array([0, 1, 2])

## __Given the X numpy matrix, show the last row elements__

In [57]:
X=np.arange(15).reshape(5,3)

In [58]:
X[-1]

array([12, 13, 14])

## __Given the X numpy matrix, show the first element on first row__

In [59]:
X=np.arange(15).reshape(5,3)

In [60]:
X[0][0]

0

## __Given the X numpy matrix, show the last element on last row__

In [61]:
X=np.arange(15).reshape(5,3)

In [62]:
X[-1][-1]

14

## __Given the X numpy matrix, show the middle row elements__

In [63]:
X=np.arange(15).reshape(5,3)

In [68]:
X[1:-1,1:-1]

array([[ 4],
       [ 7],
       [10]])

## __Given the X numpy matrix, show the first two elements on the first two rows__

In [69]:
X=np.arange(15).reshape(5,3)

In [71]:
X[:2,:2]

array([[0, 1],
       [3, 4]])

## __Given the X numpy matrix, show the last two elements on the last two rows__

In [2]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [3]:
X[-2:,-2:]

array([[11, 12],
       [15, 16]])

### __Array Manipulation__

## __Convert the given integer numpy array to float__

In [4]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [8]:
X=np.array(X,dtype= float)

In [9]:
X

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

## __Reverse the given numpy array (first element becomes last)__

In [10]:
X=np.arange(5)

In [11]:
X[::-1]

array([4, 3, 2, 1, 0])

## __Order (sort) the given numpy array__

In [18]:
X = [0, 10, -5, 40, -3]

X.sort()

X

[-5, -3, 0, 10, 40]

## __Given the X numpy array, set the fifth element equal to 1__

In [19]:
X = [0, 10, -5, 40, -3]

In [20]:
X[4]=1

In [21]:
X

[0, 10, -5, 40, 1]

## __Given the X numpy array, change the 50 with a 40__

In [22]:
X = np.array([10, 20, 30, 50])

In [23]:
X[3]=40

In [24]:
X

array([10, 20, 30, 40])

## __Given the X numpy matrix, change the last row with all 1__

In [25]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [26]:
X[-1]=np.ones(4)

In [27]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

## __Given the X numpy matrix, change the last item on the last row with a 0__

In [28]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [31]:
X[-1][-1]=0

In [32]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

## __Given the X numpy matrix, add 5 to every element__

In [33]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [36]:
X+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### __Boolean Arrays__(_also called masks_)

## __Given the X numpy array, make a mask showing negative elements__

In [37]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [40]:
mask =X<0

In [41]:
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

## __Given the X numpy array, get the negative elements__

In [42]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [44]:
X[X<0]

array([-1, -4, -9])

## __Given the X numpy array, get numbers higher than 5__

In [46]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [47]:
X[X>5]

array([ 6, 10])

## __Given the X numpy array, get numbers higher than the elements mean__

In [48]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [50]:
X[X>X.mean()]

array([ 2,  5,  6, 10])

## __Given the X numpy array, get numbers equal to 2 or 10__

In [51]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [54]:
X[(X==2)|(X==10)]

array([ 2, 10])

# __Logic Function__

## __Given the X numpy array, return True if none of its elements is zero__

In [55]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [56]:
X.all()

False

## __Given the X numpy array, return True if any of its elements is zero__

In [57]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [58]:
X.any()

True

### __Summary statistics__

## __Given the X numpy array, show the sum of its elements__

In [59]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [60]:
X.sum()

43

## __Given the X numpy array, show the mean value of its elements__

In [59]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [61]:
X.mean()

4.777777777777778

## __Given the X numpy matrix, show the sum of its columns__

In [62]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [63]:
X.sum(axis=0)

array([28, 32, 36, 40])

## __Given the X numpy matrix, show the mean value of its rows__

In [64]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [65]:
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

## __Given the X numpy array, show the max value of its elements__

In [66]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

In [67]:
X.max()

10