In [1]:
import numpy as np
print(np.__version__)

1.26.2


## __Create A numpy array filled with 10 zeros__

In [2]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## __Create a numpy arrays with values ranging from 10to49__

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## __Create a numpy matrix of 2*2 filled with ones__

In [8]:
np.array([1]*4).reshape(2,2)

array([[1, 1],
       [1, 1]])

In [11]:
np.ones([2,2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

## __Create a numpy matrix of 3*2 float ones__

In [17]:
a=np.ones([3,2], dtype=float)

In [18]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### __Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.__

In [23]:
X=np.arange(4, dtype=np.int8).reshape(2,2)

In [24]:
np.ones_like(X)

array([[1, 1],
       [1, 1]], dtype=int8)

### __Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.__

In [27]:
X=np.arange(100, dtype=np.int8).reshape(4,5,5)

In [28]:
np.zeros_like(X)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

## __Create a numpy matrix of 4*4 integers, filled with fives.__

In [29]:
np.ones([4,4], dtype=np.int8)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

### __Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.__

In [31]:
X=np.arange(49).reshape(7,7)

In [33]:
np.ones_like(X)*7

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

## __Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.__

In [3]:
np.identity(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## __Create a numpy array, filled with 3 random integer values between 1 and 10.__

In [7]:
np.random.randint(10, size=3)

array([6, 0, 9])

## __Create a 3\*3\*3 numpy matrix, filled with random float values.__

In [12]:
np.random.uniform(100, size=(3,3,3))

array([[[ 1.27268444, 45.78763072, 32.66249179],
        [36.71050311, 99.23552686, 43.50163591],
        [17.71520473, 50.70653551, 23.9883311 ]],

       [[92.5279462 , 92.9028968 , 27.25282   ],
        [33.70196089, 83.0423185 , 28.92920066],
        [62.62330478, 95.32499268,  1.7620164 ]],

       [[75.50897631, 89.98545862, 55.83724059],
        [20.8562553 ,  7.84070088, 80.10688766],
        [94.25725201, 21.26032832, 88.90919774]]])

In [10]:
np.random.randn(3,3,3)

array([[[-2.59448609,  2.1661206 ,  2.24996551],
        [-2.04895487,  0.24543163,  1.22984333],
        [ 0.41352028, -0.45584616,  0.58392554]],

       [[ 1.11689008, -1.52484373,  1.23405454],
        [ 0.67999612,  1.10891143,  1.06079394],
        [ 0.70366801,  0.9896751 , -0.23295808]],

       [[ 0.04397099, -0.26360133, -0.58902829],
        [ 1.53294586, -0.0890642 , -1.4562339 ],
        [-0.98721936, -0.38513704, -0.67670173]]])

## __Given the X python list convert it to an Y numpy array__

In [19]:
X=[1,2,3,4]

In [24]:
print(X, type(X))

[1, 2, 3, 4] <class 'list'>


In [22]:
Y=np.array(X)

In [25]:
print(Y, type(Y))

[1 2 3 4] <class 'numpy.ndarray'>


## __Given the X numpy array, make a copy and store it on Y.__

In [28]:
x=np.array([5,5,5])

In [29]:
y=np.copy(x)

In [30]:
y

array([5, 5, 5])