In [2]:
import sys
import numpy as np

## __Basic Numpy Array__

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
b = np.array(["Hello",1])

In [5]:
a[1]

2

In [8]:
b[[0,1]]

array(['Hello', '1'], dtype='<U11')

In [9]:
a.dtype

dtype('int32')

In [12]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [14]:
a = np.array([1,2,3,4,5], dtype=np.int8)

In [15]:
a.dtype

dtype('int8')

## __Dimensions and shape__

In [42]:
A=np.array([
    #0,1,2
    [1,2,3],#0
    [4,5,6],#1
    [7,8,9]#3
])

In [25]:
A.shape #gives rows and columns

(2, 3)

In [23]:
A.ndim #gives dimension here we have 1 vertical and one horizontal so 2 

2

In [24]:
A.size #no. of elements we have

6

In [27]:
B=np.array([
    [
        [1,2],
        [2,3]
    ],
    [
        [3,4],
        [4,5]
    ]
])

In [28]:
B.shape

(2, 2, 2)

In [29]:
B.ndim

3

In [30]:
B.size

8

In [38]:
B[0][0][0]

1

In [40]:
B[0,0,0]

1

In [43]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
A[:,:2] #from all row[0,2] upto column [0,1] as the 2 in {:2} is not included 

array([[1, 2],
       [4, 5],
       [7, 8]])

In [51]:
A[:,0::2] #if not understood slicing tut must be read 

array([[1, 3],
       [4, 6],
       [7, 9]])

In [52]:
A[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
A[0]=np.array([0,0,0]) #modifing the 1st row of a to be [0,0,0]

In [55]:
A[1]=np.array([1,1,1])

In [56]:
A[2]=np.array([2,2,2])

In [57]:
A

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [61]:
A[2]=22 #numpy will modify every value at 3rd row of A to 22

In [60]:
A

array([[ 0,  0,  0],
       [ 1,  1,  1],
       [22, 22, 22]])

## __Statistics__

In [3]:
a = np.array([1,2,3,4,5])

In [62]:
a.sum()

15

In [63]:
a.mean()

3.0

In [64]:
a.std()

1.4142135623730951

In [65]:
a.var()

2.0

In [69]:
A=np.array([
    #0,1,2
    [1,2,3],#0
    [4,5,6],#1
    [7,8,9]#3
])

In [70]:
A.sum(axis=0) #axis[0]==column

array([12, 15, 18])

In [71]:
A.sum(axis=1) #axis[1]==row

array([ 6, 15, 24])

In [72]:
A.mean(axis=0)

array([4., 5., 6.])

In [74]:
B=np.array([
    [[1,2],[2,3]],
    [[3,4],[4,5]]
])

In [75]:
B.sum(axis=0)

array([[4, 6],
       [6, 8]])

In [76]:
B.sum(axis=1)

array([[3, 5],
       [7, 9]])

In [78]:
B[0].sum(axis=0)

array([3, 5])

## __Broadcasting and Vectorized operation__

In [5]:
a=np.arange(5)

In [6]:
a

array([0, 1, 2, 3, 4])

In [8]:
a+10 #creates a new array and returns it doesn't overwrites the original array

array([10, 11, 12, 13, 14])

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
a*10

array([ 0, 10, 20, 30, 40])

In [13]:
a+=10 #(a=a+10) now the original array is overwrited

In [12]:
a

array([10, 11, 12, 13, 14])

In [14]:
b=np.arange(5)

In [16]:
a+b #two arrays can be operated easily but the no. of elements and dimensions should match

array([20, 22, 24, 26, 28])

In [30]:
a=np.arange(12).reshape(2,2,3)

In [31]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## **Boolean Arrays**
_(Also called masks)_

In [32]:
a=np.arange(10)

In [33]:
b=a<5

In [34]:
b

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [35]:
a[b]

array([0, 1, 2, 3, 4])

In [36]:
a[a<5]

array([0, 1, 2, 3, 4])

In [37]:
a.mean()

4.5

In [39]:
a[a>a.mean()]

array([5, 6, 7, 8, 9])

In [40]:
a[~(a>a.mean())]

array([0, 1, 2, 3, 4])

In [45]:
a[(a<5) | (a%2==0)]

array([0, 1, 2, 3, 4, 6, 8])

In [46]:
a[(a<8) & (a%2==0)]

array([0, 2, 4, 6])

In [49]:
a=np.random.randint(100, size=(3,3))

In [50]:
a

array([[33, 32,  8],
       [22, 62,  1],
       [26, 25, 85]])

In [51]:
a>30

array([[ True,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [52]:
a[a>30]

array([33, 32, 62, 85])

## __Linear Algebra__

In [6]:
a=np.arange(1,10).reshape(3,3)

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b=np.arange(1,7).reshape(3,2)

In [12]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a.dot(b) #dot product

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [18]:
a@b #matrix multiplication

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [20]:
b.T #transpose

array([[1, 3, 5],
       [2, 4, 6]])

In [21]:
b.T @ a

array([[48, 57, 66],
       [60, 72, 84]])