In [1]:
import numpy as np
print(np.__version__)

1.26.2


## __Create A numpy array filled with 10 zeros__

In [2]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## __Create a numpy arrays with values ranging from 10to49__

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## __Create a numpy matrix of 2*2 filled with ones__

In [8]:
np.array([1]*4).reshape(2,2)

array([[1, 1],
       [1, 1]])

In [11]:
np.ones([2,2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

## __Create a numpy matrix of 3*2 float ones__

In [17]:
a=np.ones([3,2], dtype=float)

In [18]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### __Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.__

In [23]:
X=np.arange(4, dtype=np.int8).reshape(2,2)

In [24]:
np.ones_like(X)

array([[1, 1],
       [1, 1]], dtype=int8)

### __Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.__

In [27]:
X=np.arange(100, dtype=np.int8).reshape(4,5,5)

In [28]:
np.zeros_like(X)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

## __Create a numpy matrix of 4*4 integers, filled with fives.__

In [29]:
np.ones([4,4], dtype=np.int8)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

### __Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.__

In [31]:
X=np.arange(49).reshape(7,7)

In [33]:
np.ones_like(X)*7

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])